services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    env_file:
      - .env  # Ou un chemin absolu si nécessaire
    ports:
      - "8000:8000"
    volumes:
      - .:/app/classes
    container_name: app-container
  

  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres-container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d miniproject"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    depends_on:
      - database
    ports:
      - "8080:8080"
    container_name: adminer-container

volumes:
  postgres_data:
